# Meowrch Kernel Module Optimizations
# Based on CachyOS optimizations for maximum performance and stability

#===> NVIDIA GPU Optimizations
# NVreg_InitializeSystemMemoryAllocations=0 (Default 1) - Disables clearing
# system memory allocation before using it for the GPU. Potentially improves
# performance, but at the cost of increased security risks. Write "options
# nvidia NVreg_InitializeSystemMemoryAllocations=1" in
# /etc/modprobe.d/nvidia.conf, if you want to return the default value. Note:
# It is possible to use more memory (?)

options nvidia NVreg_InitializeSystemMemoryAllocations=0 \
    NVreg_DynamicPowerManagement=0x02
###############################################################################

#===> AMD GPU Optimizations
###############################################################################
# Force using of the amdgpu driver for Southern Islands (GCN 1.0+) and Sea
# Islands (GCN 2.x) generations.
options amdgpu si_support=1 cik_support=1
options radeon si_support=0 cik_support=0
###############################################################################
